language: python
os: linux
dist: trusty
sudo: required
python:
  - 3.4
branches:
  only:
    - master
virtualenv:
  system_site_packages: true
install:
  - sudo apt-get update
  - sudo apt-get install python3-coverage
  - sudo apt-get install gir1.2-gstreamer-1.0 gir1.2-gst-plugins-base-1.0
  - sudo pip install six packaging appdirs
  - sudo easy_install -U setuptools
  - sudo pip install
  - make init
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
script:
  - nosetests --with-coverage --cover-erase --cover-html --cover-package=adblockradio --all-modules --cover-branches
  